draw_config:
  key_rx: 4.0
  key_ry: 4.0
  inner_pad_w: 1.0
  inner_pad_h: 1.0
  outer_pad_w: 10.0
  outer_pad_h: 16.0
  line_spacing: 1.0
  combo_h: 24.0
  append_colon_to_layer_header: false
  small_pad: 4.0
  shrink_wide_legends: 5
  glyph_tap_size: 18
  glyph_hold_size: 12
  glyph_shifted_size: 10
  svg_style: |
    /* latin-ext */
    @font-face {
      font-family: 'REM';
      font-style: normal;
      font-weight: 500;
      font-display: swap;
      src: url(https://fonts.gstatic.com/s/rem/v2/WnzgHAIoSDyHbRjfsYumpRvUPPDqnTMea6iNbBRekzKm.woff) format('woff');
      unicode-range: U+0100-02AF, U+0304, U+0308, U+0329, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
    }
    /* latin */
    @font-face {
      font-family: 'REM';
      font-style: normal;
      font-weight: 500;
      font-display: swap;
      src: url(https://fonts.gstatic.com/s/rem/v2/WnzgHAIoSDyHbRjfsYumpRvUPPDqnT0ea6iNbBRekw.woff) format('woff');
      unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
    }

    /* inherit to force styles through use tags */
    svg path {
        fill: inherit;
    }

    /* font and background color specifications */
    svg.keymap {
        /*
         * ====================
         * Theme Variables
         * ====================
         */
        --logo-path: none;
        --logo-size: 12%;
        --logo-position: 49.5% 5%;

        /* === Colors === */
        --color--material--blue-gray--50: rgb(236, 239, 241);
        --color--material--blue-gray--100: rgb(207, 216, 220);
        --color--material--blue-gray--200: rgb(176, 190, 197);
        --color--material--blue-gray--300: rgb(144, 164, 174);
        --color--material--blue-gray--400: rgb(120, 144, 156);
        --color--material--blue-gray--500: rgb(96, 125, 139);
        --color--material--blue-gray--600: rgb(84, 110, 122);
        --color--material--blue-gray--700: rgb(69, 90, 100);
        --color--material--blue-gray--800: rgb(55, 71, 79);
        --color--material--blue-gray--900: rgb(38, 50, 56);

        --color--bg: rgb(35, 40, 46);
        --color--text: var(--color--material--blue-gray--900);

        --color--layer--text: #90a4ae;

        --color--key--bg: var(--color--material--blue-gray--50);
        --color--key--border: white;
        --color--key--text--tap: var(--color--text);
        --color--key--text--shifted: var(--color--material--blue-gray--400);
        --color--key--text--hold: var(--color--layer--text);

        --color--combo--bg: rgba(251, 216, 93, 0.9);
        --color--combo--border: transparent;
        --color--combo--dendron: var(--color--material--blue-gray--300);
        --color--combo--text--tap: var(--color--text);
        --color--combo--text--shifted: var(--color--combo--text--tap);
        --color--combo--text--hold: var(--color--combo--text--tap);

        --color--trans--bg: var(--color--material--blue-gray--100);
        --color--trans--border: var(--color--material--blue-gray--200);
        --color--trans--text--tap: var(--color--material--blue-gray--200);
        --color--trans--text--shifted: var(--color--trans--text--tap);
        --color--trans--text--hold: var(--color--trans--text--tap);

        --color--none--bg: var(--color--trans--bg);
        --color--none--border: var(--color--trans--border);
        --color--none--text--tap: var(--color--trans--text--tap);
        --color--none--text--shifted: var(--color--trans--text--shifted);
        --color--none--text--hold: var(--color--trans--text--hold);

        --color--ghost--bg: var(--color--trans--bg);
        --color--ghost--border: var(--color--trans--border);
        --color--ghost--text--tap: var(--color--trans--text--tap);
        --color--ghost--text--shifted: var(--color--trans--text--shifted);
        --color--ghost--text--hold: var(--color--trans--text--shifted);

        /*
         * ====================
         * /End Theme Variables
         * ====================
         */


        font-family: REM,SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
        font-size: 16px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        fill: var(--color--text);
        background-color: var(--color--bg);
        background-image: var(--logo-path);
        background-repeat: no-repeat;
        background-position: var(--logo-position);
        background-size: var(--logo-size) auto;
    }

    /* default key styling */
    .key {
        fill: var(--color--key--bg);
        stroke: var(--color--key--border);
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
        line-height: 1;
    }

    /* styling for layer labels */
    text.label {
        font-weight: bold;
        text-anchor: start;
        paint-order: stroke;
        fill: var(--color--layer--text);
        dominant-baseline: hanging;
    }

    .shifted {
        font-size: 11px;
        text-anchor: middle;
        dominant-baseline: hanging;
    }
    .hold {
        font-size: 11px;
        text-anchor: middle;
        dominant-baseline: auto;
    }

    .tap:not(.combo) {
        fill: var(--color--key--text--tap);
    }
    .shifted:not(.combo) {
        fill: var(--color--key--text--shifted);
    }
    .hold:not(.combo) {
        fill: var(--color--key--text--hold);
    }

    /*
     * Combos
     */
    rect.combo {
        fill: var(--color--combo--bg);
        stroke: var(--color--combo--border);
    }
    /* dendrons */
    path.combo {
        stroke-width: 1;
        stroke: var(--color--combo--dendron);
        stroke-dasharray: 2, 2;
        fill: none;
    }
    .combo.hold,
    .combo.shifted {
        font-size: 8px;
    }
    .combo.tap {
        font-size: 11px;
        fill: var(--color--combo--text--tap);
    }
    .combo.shifted {
        fill: var(--color--combo--text--shifted);
        dominant-baseline: mathematical;
    }
    .combo.hold {
        fill: var(--color--combo--text--hold);
    }

    /*
     * Transparent, None, and Ghost Keys
     */

    /*
     * Transparent Keys
     */
    .key.trans {
        fill: var(--color--trans--bg);
        stroke: var(--color--trans--border);
    }
    .trans.tap {
        font-size: 11px;
        fill: var(--color--trans--text--tap);
    }
    .trans.shifted {
        fill: var(--color--trans--text--shifted);
    }
    .trans.hold {
        fill: var(--color--trans--text--hold);
    }

    /*
     * None Keys
     */
    .key.none {
        fill: var(--color--none--bg);
        stroke: var(--color--none--border);
    }
    .none.tap {
        font-size: 11px;
        fill: var(--color--none--text--tap);
    }
    .none.shifted {
        fill: var(--color--none--text--shifted);
    }
    .none.hold {
        fill: var(--color--none--text--hold);
    }

    /*
     * Ghost Keys
     */
    .key.ghost {
        fill: var(--color--ghost--bg);
        stroke: var(--color--ghost--border);
    }
    .ghost.tap {
        font-size: 11px;
        fill: var(--color--ghost--text--tap);
    }
    .ghost.shifted {
        fill: var(--color--ghost--text--shifted);
    }
    .ghost.hold {
        fill: var(--color--ghost--text--hold);
    }


    /*
     * Overrides
     */

    .tap + .hold.mdi\:apple-keyboard-command + .shifted,
    .tap + .hold.mdi\:apple-keyboard-option + .shifted {
        transform: translateY(8px);
    }


    /* Start Tabler Icons Cleanup */
    /* cannot use height/width with glyphs */
    .icon-tabler > path {
        fill: inherit;
        stroke: inherit;
    }
    /* hide tabler's default box */
    .icon-tabler > path[stroke="none"][fill="none"] {
        visibility: collapse;
    }
    /* End Tabler Icons Cleanup */

parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  raw_binding_map:
    # Layers
    "&smart_num L2 0":
      shifted: $$mdi:alpha-w-box$$
      tap: L2
      hold: $$mdi:gesture-tap-hold$$

    # Modifiers
    "&caps_word": $$mdi:alpha-w-box$$
    "&kt RSHIFT":
      tap: $$mdi:apple-keyboard-shift$$
      hold: $$mdi:toggle-switch$$

    # Empty
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none

    # Bluetooth
    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 5
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch-outline$$
      hold: $$mdi:bluetooth$$

    # Reset
    "&sys_reset":
      tap: $$mdi:backup-restore$$
    "&bootloader":
      tap: $$mdi:progress-download$$

  # ZMK
  zmk_keycode_map:
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      tap: "="
      shifted: "+"
    PLUS: +
    MINUS:
      tap: "-"
      shifted: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '"'
    DQT: '"'

    LESS_THAN: <
    LT: <
    DOT:
      tap: "."
      shifted: ">"
    COMMA:
      tap: ","
      shifted: "<"
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    LBKT:
      tap: "["
      shifted: "{"
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    RBKT:
      tap: "]"
      shifted: "}"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "~"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    # Numbers
    N1:
      tap: 1
      shifted: "!"
    N2:
      tap: 2
      shifted: "@"
    N3:
      tap: 3
      shifted: "#"
    N4:
      tap: 4
      shifted: "$"
    N5:
      tap: 5
      shifted: "%"
    N6:
      tap: 6
      shifted: "^"
    N7:
      tap: 7
      shifted: "&"
    N8:
      tap: 8
      shifted: "*"
    N9:
      tap: 9
      shifted: "("
    N0:
      tap: 0
      shifted: ")"

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    # "Meh" key
    LS(LC(LALT)): $$mdi:star-three-points$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$

    # Whitespace
    ENTER: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE: $$mdi:backspace$$
    BSPC: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$

    # System
    C_POWER: $$mdi:power$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL:
      shifted: $$mdi:alpha-w-box$$
      tap: L1
      hold: $$mdi:circle-off-outline$$

    # Zoom
    RG(RS(A)):
      tap: $$mdi:microphone$$
      hold: zoom
    RG(RS(V)):
      tap: $$mdi:video$$
      hold: zoom

  zmk_combos:
    combo_to_2:
      align: top
    combo_to_3:
      align: top
    combo_bt_clear:
      align: top
    combo_mute:
      align: top
      offset: 0.15
    combo_minus:
      key:
        shifted: "_"
        hold: "-"
    combo_equal:
      key:
        shifted: "+"
        hold: "="
    combo_backslash:
      key:
        shifted: "|"
        hold: \
    combo_lbkt:
      key:
        shifted: "{"
        hold: "["
    combo_rbkt:
      key:
        shifted: "}"
        hold: "]"
